# Generated by Django 4.1.3 on 2022-12-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_chats',
            field=models.BooleanField(default=False),
        ),
    ]
