# Generated by Django 4.1.3 on 2022-12-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_allow_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allow_chats',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allow_chats_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allow_chats_public',
            field=models.BooleanField(default=False),
        ),
    ]
