# Generated by Django 4.1.3 on 2022-12-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_allow_chats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allow_chats_private',
            field=models.BooleanField(default=False, verbose_name='Allow Private Chats'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allow_chats_public',
            field=models.BooleanField(default=False, verbose_name='Allow Public Chats'),
        ),
    ]
